
name: Build and Push Docker Tag

on:
  push:
    tags:
      - "*.*"

jobs:
  publish-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION//[!a-zA-Z0-9._-]/}
          echo "::set-output name=version::$VERSION"

      - name: Publish Docker tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/passkey:${{ steps.vars.outputs.version }}
