name: Build Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      working-directory: go
      run: go build -v ./...

    - name: Test
      working-directory: go
      run: go test

    - name: Test
      working-directory: go
      run: go test -v ./...
