name: Test All Modes

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build Go CLI
        run: make build

      - name: Run Go tests (incl. generator)
        run: go test ./...

      - name: Shell test
        run: bash tests/shell_test.sh

      - name: Docker test
        run: bash tests/docker_test.sh
